INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (4,'ECE');
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (5,'CSE');
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (12,'IT');
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (3,'EEE');
INSERT INTO STUDENT (STUDENT_ID,STUDENT_NAME, DEPARTMENT_ID) VALUES (12345,'RAVI',4);
INSERT INTO STUDENT (STUDENT_ID,STUDENT_NAME, DEPARTMENT_ID) VALUES (25342,'KRISHNA',5);
INSERT INTO STUDENT (STUDENT_ID,STUDENT_NAME,DEPARTMENT_ID) VALUES (34572,'JOHN',12);
INSERT INTO STUDENT (STUDENT_ID,DEPARTMENT_ID) VALUES (98762,3);
INSERT INTO SEATS (SEAT_ID,STUDENT_ID,DEPARTMENT_ID) VALUES (123,12345,4);
INSERT INTO SEATS (SEAT_ID,STUDENT_ID,DEPARTMENT_ID) VALUES (736,25342,5);
INSERT INTO SEATS (SEAT_ID,STUDENT_ID,DEPARTMENT_ID) VALUES (674,34572,12);
INSERT INTO SEATS (SEAT_ID,STUDENT_ID,DEPARTMENT_ID) VALUES (564,98762,3);






